import { useState } from 'react';
import { FiArrowLeft, FiX } from 'react-icons/fi';

const posts = [
  ['5 Easy Weeknight Dinners', 'Quick, satisfying meals for the evenings you want something homemade.', 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=85', 'Start with one dependable base: pasta, rice, eggs, or potatoes. Add a colourful vegetable, a little protein, and something bright such as lemon or herbs. A warm dinner does not need a long list of ingredients.'],
  ['Kitchen Storage Tips', 'Keep produce fresher and make the most of every grocery run.', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=85', 'Keep leafy greens dry in a container with a paper towel, store tomatoes at room temperature, and save herbs in a glass with a little water. Small habits mean fewer forgotten ingredients at the end of the week.'],
  ['Healthy Breakfast Ideas', 'Simple, colourful starts that make mornings easier.', 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=900&q=85', 'Build breakfast around a quick protein, a fruit or vegetable, and something satisfying. Eggs on toast, yogurt with fruit, or a leftover vegetable omelette are all good places to begin.'],
  ['Cooking With Leftovers', 'A few smart habits can turn yesterday into tonight’s best dinner.', 'https://images.unsplash.com/photo-1543352634-a1c51d9f1fa7?auto=format&fit=crop&w=900&q=85', 'Give leftovers a new role instead of simply reheating them. Roast vegetables can become a frittata, cooked rice can become a crisp skillet bowl, and a little sauce can bring a plate together.'],
];

export default function Blog() {
  const [activePost, setActivePost] = useState(null);
  if (activePost !== null) {
    const [title, excerpt, image, story] = posts[activePost];
    return <main className="mx-auto max-w-3xl px-5 py-14 sm:py-20"><button type="button" onClick={() => setActivePost(null)} className="inline-flex items-center gap-2 font-bold text-[#779500] hover:underline"><FiArrowLeft /> Back to journal</button><article className="mt-8 overflow-hidden rounded-[2rem] border border-black/5 bg-white shadow-soft dark:border-white/10 dark:bg-white/5"><img src={image} alt="" className="h-64 w-full object-cover sm:h-80" /><div className="p-7 sm:p-10"><p className="text-xs font-bold uppercase tracking-widest text-[#779500]">Kitchen notes · July {activePost + 1}, 2026</p><h1 className="mt-4 font-display text-4xl sm:text-5xl">{title}</h1><p className="mt-5 text-xl leading-relaxed opacity-70">{excerpt}</p><p className="mt-7 text-lg leading-relaxed opacity-75">{story}</p><p className="mt-5 text-lg leading-relaxed opacity-75">Chef Fox’s rule: cook with curiosity, taste as you go, and let the ingredients you already have lead the way.</p><button type="button" onClick={() => setActivePost(null)} className="btn-secondary mt-8 inline-flex items-center gap-2"><FiX /> Close story</button></div></article></main>;
  }
  return <main className="mx-auto max-w-5xl px-5 py-14 sm:py-20"><div className="text-center"><span className="eyebrow">From the kitchen journal</span><h1 className="mt-5 font-display text-5xl sm:text-6xl">A little more joy<br />in every meal.</h1><p className="mx-auto mt-4 max-w-2xl text-lg opacity-65">Weeknight ideas, pantry inspiration, and gentle cooking confidence from Chef Fox.</p></div><section className="mt-12 space-y-6">{posts.map(([title, excerpt, image], index) => <article key={title} className="grid overflow-hidden rounded-[2rem] border border-black/5 bg-white shadow-soft md:grid-cols-[.8fr_1.2fr] dark:border-white/10 dark:bg-white/5"><img src={image} alt="" className="h-56 w-full object-cover md:h-full" /><div className="p-7 sm:p-9"><p className="text-xs font-bold uppercase tracking-widest text-[#779500]">July {index + 1}, 2026 · Kitchen notes</p><h2 className="mt-3 text-2xl font-bold sm:text-3xl">{title}</h2><p className="mt-3 text-lg leading-relaxed opacity-65">{excerpt}</p><button type="button" onClick={() => setActivePost(index)} className="mt-6 font-bold text-[#779500] hover:underline">Read story →</button></div></article>)}</section></main>;
}
