import { useState } from 'react';
import { FiArrowLeft, FiClock, FiHeart, FiUsers } from 'react-icons/fi';

const recipes = [
  ['Creamy Lemon Pasta', '25 min', 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=800&q=85'],
  ['Garden Breakfast Bowl', '15 min', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=85'],
  ['Golden Veggie Toast', '18 min', 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=85'],
  ['Cozy Tomato Soup', '30 min', 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=85'],
  ['Sunday Chicken Plate', '35 min', 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=800&q=85'],
  ['Bright Berry Breakfast', '10 min', 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=800&q=85'],
];
const filters = ['Trending recipes', 'Most loved', 'Quick meals', 'Healthy', 'Vegetarian', 'Breakfast', 'Desserts'];

export default function Community() {
  const [active, setActive] = useState(null);
  if (active !== null) {
    const [name, time, image] = recipes[active];
    return <main className="mx-auto max-w-4xl px-5 py-14 sm:py-20"><button type="button" onClick={() => setActive(null)} className="inline-flex items-center gap-2 font-bold text-[#779500] hover:underline"><FiArrowLeft /> Back to community recipes</button><article className="mt-8 overflow-hidden rounded-[2rem] border border-black/5 bg-white shadow-soft dark:border-white/10 dark:bg-white/5"><img src={image} alt="" className="h-64 w-full object-cover sm:h-96" /><div className="p-7 sm:p-10"><p className="text-xs font-bold uppercase tracking-widest text-[#779500]">Community favorite</p><h1 className="mt-3 font-display text-4xl sm:text-5xl">{name}</h1><div className="mt-5 flex flex-wrap gap-3 text-sm font-semibold opacity-65"><span className="inline-flex items-center gap-1"><FiClock /> {time}</span><span className="inline-flex items-center gap-1"><FiUsers /> Serves 2</span><span className="inline-flex items-center gap-1"><FiHeart /> Loved by 248 cooks</span></div><div className="mt-9 grid gap-8 md:grid-cols-2"><section><h2 className="text-2xl font-bold">Ingredients</h2><ul className="mt-4 space-y-3 opacity-70"><li>• 2 cups seasonal vegetables</li><li>• 1 main ingredient from your pantry</li><li>• Olive oil, salt, and pepper</li><li>• Fresh herbs or lemon to finish</li></ul></section><section><h2 className="text-2xl font-bold">How to make it</h2><ol className="mt-4 space-y-3 opacity-70"><li>1. Prep all ingredients and warm a pan.</li><li>2. Cook until fragrant and golden.</li><li>3. Season, plate, and enjoy while warm.</li></ol></section></div></div></article></main>;
  }
  return <main className="mx-auto max-w-7xl px-5 py-14 sm:py-20"><span className="eyebrow">Community cookbook</span><div className="mt-5 flex flex-wrap items-end justify-between gap-5"><div><h1 className="font-display text-5xl sm:text-6xl">Made with love,<br /><span className="text-[#779500]">shared with you.</span></h1><p className="mt-4 max-w-xl text-lg opacity-65">Fresh dinner inspiration from the Fridge2Recipe community.</p></div><div className="mascot-note">🦊 Chef Fox picked these for you</div></div><div className="mt-10 flex gap-2 overflow-x-auto pb-2">{filters.map((filter, index) => <button type="button" key={filter} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold ${index === 0 ? 'bg-[#6e8700] text-white' : 'border border-black/10 bg-white/70 dark:border-white/10 dark:bg-white/5'}`}>{filter}</button>)}</div><section className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{recipes.map(([name, time, image], index) => <button type="button" onClick={() => setActive(index)} key={name} className="group overflow-hidden rounded-[1.75rem] border border-black/5 bg-white text-left shadow-soft transition duration-300 hover:-translate-y-1 hover:shadow-lg focus-visible:ring-offset-cream dark:border-white/10 dark:bg-white/5"><img src={image} alt="" className="h-48 w-full object-cover transition duration-500 group-hover:scale-105" /><span className="block p-5"><span className="text-xs font-bold uppercase tracking-wider text-[#779500]">Community favorite</span><span className="mt-2 block text-xl font-bold">{name}</span><span className="mt-4 flex items-center justify-between text-sm opacity-60"><span className="inline-flex items-center gap-1"><FiClock />{time}</span><span className="inline-flex items-center gap-1"><FiHeart /> 248</span></span></span></button>)}</section></main>;
}
