import { FiBookmark, FiClock, FiCopy, FiHeart, FiPrinter, FiShare2, FiUsers } from 'react-icons/fi';
import toast from 'react-hot-toast';
import RecipeImage, { recipeImageFor } from './RecipeImage';

export default function RecipeHero({ recipe, favorite, onFavorite, onSave }) {
  const copy = async () => { try { await navigator.clipboard.writeText(`${recipe.recipeName}\n\n${recipe.steps.map((step, index) => `${index + 1}. ${step.instruction}`).join('\n')}`); toast.success('Copied successfully.'); } catch { toast.error('Copy is unavailable in this browser.'); } };
  const share = async () => { try { if (navigator.share) await navigator.share({ title: recipe.recipeName, text: recipe.description }); else await copy(); } catch (error) { if (error.name !== 'AbortError') toast.error('Could not share this recipe.'); } };
  const actions = [[FiHeart, onFavorite, favorite ? 'Saved favorite' : 'Favorite'], [FiBookmark, onSave, 'Save'], [FiCopy, copy, 'Copy'], [FiShare2, share, 'Share'], [FiPrinter, () => window.print(), 'Print']];
  const image = recipeImageFor(recipe);
  return <section className="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-[#4b2513] via-[#9d481b] to-orange p-5 text-white shadow-soft sm:p-7"><div className="absolute -right-12 -top-16 h-64 w-64 rounded-full bg-sun/30 blur-2xl" /><div className={`relative grid gap-7 ${image ? 'md:grid-cols-[1.15fr_.85fr] md:items-stretch' : ''}`}><div className="py-2 sm:p-3"><div className="mb-6 flex flex-wrap gap-2"><span className="rounded-full bg-white/15 px-3 py-1 text-sm">{recipe.difficulty}</span><span className="flex items-center gap-1 rounded-full bg-white/15 px-3 py-1 text-sm"><FiClock /> {recipe.time}</span><span className="flex items-center gap-1 rounded-full bg-white/15 px-3 py-1 text-sm"><FiUsers /> {recipe.servings}</span></div><h1 className="font-serif text-4xl leading-tight sm:text-6xl">{recipe.recipeName}</h1><p className="mt-4 max-w-xl text-lg text-white/80">{recipe.description}</p><div className="mt-7 flex flex-wrap gap-2">{actions.map(([Icon, action, label]) => <button type="button" key={label} onClick={action} className="inline-flex items-center gap-2 rounded-xl bg-white/15 px-3 py-2 text-sm font-semibold transition hover:bg-white/25"><Icon /> {label}</button>)}</div></div>{image && <div className="relative"><RecipeImage recipe={recipe} /><div className="absolute -bottom-4 left-4 rounded-2xl border border-white/30 bg-[#fffaf5]/95 px-3 py-2 text-ink shadow-soft"><span className="mr-2 text-2xl">🦊</span><span className="inline-block align-middle text-xs"><small className="block uppercase tracking-wider opacity-50">Chef Fox says</small><b>Let’s make it delicious.</b></span></div></div>}</div></section>;
}
